/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LayoutProse {
    }
    interface NavFooter {
    }
    interface NavHeader {
    }
}
declare global {
    interface HTMLLayoutProseElement extends Components.LayoutProse, HTMLStencilElement {
    }
    var HTMLLayoutProseElement: {
        prototype: HTMLLayoutProseElement;
        new (): HTMLLayoutProseElement;
    };
    interface HTMLNavFooterElement extends Components.NavFooter, HTMLStencilElement {
    }
    var HTMLNavFooterElement: {
        prototype: HTMLNavFooterElement;
        new (): HTMLNavFooterElement;
    };
    interface HTMLNavHeaderElement extends Components.NavHeader, HTMLStencilElement {
    }
    var HTMLNavHeaderElement: {
        prototype: HTMLNavHeaderElement;
        new (): HTMLNavHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "layout-prose": HTMLLayoutProseElement;
        "nav-footer": HTMLNavFooterElement;
        "nav-header": HTMLNavHeaderElement;
    }
}
declare namespace LocalJSX {
    interface LayoutProse {
    }
    interface NavFooter {
    }
    interface NavHeader {
    }
    interface IntrinsicElements {
        "layout-prose": LayoutProse;
        "nav-footer": NavFooter;
        "nav-header": NavHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "layout-prose": LocalJSX.LayoutProse & JSXBase.HTMLAttributes<HTMLLayoutProseElement>;
            "nav-footer": LocalJSX.NavFooter & JSXBase.HTMLAttributes<HTMLNavFooterElement>;
            "nav-header": LocalJSX.NavHeader & JSXBase.HTMLAttributes<HTMLNavHeaderElement>;
        }
    }
}
