/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FaqItem } from "../../services/faq/FaqItem";
export { FaqItem } from "../../services/faq/FaqItem";
export namespace Components {
    interface ExampleExpand {
        "open": boolean;
    }
    interface ExampleExpandHeader {
        "item": FaqItem;
    }
    interface ExampleFaq {
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLExampleExpandElement extends Components.ExampleExpand, HTMLStencilElement {
    }
    var HTMLExampleExpandElement: {
        prototype: HTMLExampleExpandElement;
        new (): HTMLExampleExpandElement;
    };
    interface HTMLExampleExpandHeaderElement extends Components.ExampleExpandHeader, HTMLStencilElement {
    }
    var HTMLExampleExpandHeaderElement: {
        prototype: HTMLExampleExpandHeaderElement;
        new (): HTMLExampleExpandHeaderElement;
    };
    interface HTMLExampleFaqElement extends Components.ExampleFaq, HTMLStencilElement {
    }
    var HTMLExampleFaqElement: {
        prototype: HTMLExampleFaqElement;
        new (): HTMLExampleFaqElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "example-expand": HTMLExampleExpandElement;
        "example-expand-header": HTMLExampleExpandHeaderElement;
        "example-faq": HTMLExampleFaqElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ExampleExpand {
        "open"?: boolean;
    }
    interface ExampleExpandHeader {
        "item"?: FaqItem;
    }
    interface ExampleFaq {
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "example-expand": ExampleExpand;
        "example-expand-header": ExampleExpandHeader;
        "example-faq": ExampleFaq;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-expand": LocalJSX.ExampleExpand & JSXBase.HTMLAttributes<HTMLExampleExpandElement>;
            "example-expand-header": LocalJSX.ExampleExpandHeader & JSXBase.HTMLAttributes<HTMLExampleExpandHeaderElement>;
            "example-faq": LocalJSX.ExampleFaq & JSXBase.HTMLAttributes<HTMLExampleFaqElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
